spring:
  jwt:
    secret: ApenasParaEncriptar
    expiration: 30000
  main:
    banner-mode: "off"
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://192.168.0.10:5432/curso
    username: pi
    password: postgres
    driver-class-name: org.postgresql.Driver
    #initialization-mode: always
    
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 8080